---
title: "Metal & Enchanting Based Money Supply"
output: html_notebook
---

```{r One-off Gold, Silver,and Copper Money Supply }
##**Mining***##
#Assuming all gold is produced in Country X, all gold is of same grade, and miners are paid a set wage.

#Miners produce 1 unit of gold per week
#There are L miners total with L_g miners mining gold
L <- 100
L_g <- floor(1/3 * L)
L_s <- floor(1/3 * L)
L_c <- floor(1/3 * L)
#Gold Produced in a week
g <- 1 * L_g
s <- 1 * L_s
c <- 1 * L_c
#Miners paid 1 enchanted gold coin per week
wage_g <- 1
wage_s <- 1
wage_c <- 1
#cost of Mining Gold
glaborcost <- wage_g * L_g
slaborcost <- wage_s * L_s
claborcost <- wage_c * L_c

##**Minting**##
#Assume e is percent of unit of gold lost in minting

e <- runif(1, 0, 0.0002)
#For every unit of gold, x coins can be minted (with spillage accounted for)
x_g <- 10
x_s <- 10
x_c <- 10
M_g <- floor(x_g * g * (1-e))
M_s <- floor(x_s * s * (1-e))
M_c <- floor(x_c * c * (1-e))

#Cost of minting
gmintcost <- 10
smintcost <- 10
cmintcost <- 10

#Spillage and loss accounting
## When implementing repeat simulations, keep stock of difference in M_g with and without floor() to accumulate so less loss

spill_g <- x_g * g - M_g
spill_s <- x_s * s - M_s
spill_c <- x_c * c - M_c

loss_g <- spill_g * 1
loss_s <- spill_s * 0.1
loss_c <- spill_c * 0.01


##**Enchanting Gold**##
#*Country Y is sent M coins to enchant which they do with a*100% success rate
a_g <- 1
a_c <- 1
a_s <- 1

g_enchant <- a_g * M_g
s_enchant <- a_s * M_s
c_enchant <- a_c * M_c
##**Returning Gold*##
#Country Y keeps y% of the coins enchanted as payment since they are the only ones capable of this service.
y_g <- 0.1
y_s <- 0.1
y_c <- 0.1

greserve <- y_g * g_enchant
sreserve <- y_s * s_enchant
creserve <- y_c * c_enchant

gsupply <- g_enchant - greserve
ssupply <- s_enchant - sreserve
csupply <- c_enchant - creserve

#Repaying the cost to create this we have the following cost 
gcost <- glaborcost + gmintcost
scost <- slaborcost + smintcost
ccost <- claborcost + smintcost
#Finally the actual value of generated Money Supply in terms of gold
moneysupply <- (gsupply * 1 - gcost) +  (ssupply * 0.1 - scost) + (csupply * 0.001 - ccost)
moneysupply
```

```{r Mining_Setup Simulation Set up}

run_worker <- function(T, t, start_x = 20, min_draw = 1, max_draw = 20) {
  
  x <- start_x
  runs <- 0
  successes <- 0
  
  max_runs <- floor(T / t)
  
  while (runs < max_runs) {
    
    draw <- runif(1, min = min_draw, max = max_draw)
    runs <- runs + 1
    
    if (draw < x) {
      x <- x - 1
    } else {
      successes <- successes + 1
      x <- start_x
    }
  }
  
  return(list(
    successes = successes,
    runs = runs
  ))
}

simulate_workers <- function(n_workers, T, t, start_x = 20, min_draw = 1, max_draw = 20) {
  
  worker_results <- replicate(
    n_workers,
    run_worker(
      T = T,
      t = t,
      start_x = start_x,
      min_draw = min_draw,
      max_draw = max_draw
    ),
    simplify = FALSE
  )
  
  worker_df <- do.call(
    rbind,
    lapply(worker_results, as.data.frame)
  )
  
  rownames(worker_df) <- NULL
  
  return(worker_df)
}
```

```{r Mining_Simulation}
set.seed(1234)

workers <- 100000
T <- 100
t <- 5
results <- simulate_workers(
    workers,
    T,
    t
  )

#using the number of successful mining attempts, a d4 is used to determine how many ounces of ore is collected.
successes <- sum(results$successes)
successes
sum(runif(successes, 1, 4))

#0.1125 troy ounces in a coin

```

```{r Updated Setup}
# ============================================================
# PARAMETERS
# ============================================================

params <- list(
  T = 100,
  t = 5,
  
  start_x = 20,
  task_min = 1,
  task_max = 20,
  
  output_min = 1,
  output_max = 4
)

# ============================================================
# BACKEND FUNCTIONS
# ============================================================

run_worker <- function(params) {
  
  x <- params$start_x
  runs <- 0
  successes <- 0
  
  max_runs <- floor(params$T / params$t)
  
  while (runs < max_runs) {
    
    draw <- runif(
      1, 
      min = params$task_min, 
      max = params$task_max
    )
    
    runs <- runs + 1
    
    if (draw < x) {
      x <- x - 1
    } else {
      successes <- successes + 1
      x <- params$start_x
    }
  }
  
  return(successes)
}

produce_output <- function(successes, params) {
  
  if (successes == 0) {
    return(0)
  }
  
  output <- sum(
    runif(
      successes, 
      min = params$output_min, 
      max = params$output_max
    )
  )
  
  return(output)
}

produce_ore <- function(L, params = params) {
  
  worker_outputs <- replicate(
    L,
    {
      successes <- run_worker(params)
      produce_output(successes, params)
    }
  )
  
  total_output <- sum(worker_outputs)
  
  return(total_output)
}

# ============================================================
# MODEL
# ============================================================

```

```{r Repeated Simulation of Gold Production}
##**Mining***##
set.seed(61234)
#Assuming all gold is produced in Country X, all gold is of same grade, and miners are paid a set wage.

#Miners produce 1 unit of gold per week
#There are L miners total with L_g miners mining gold
L <- 100000
L_g <- floor(1/3 * L)
L_s <- floor(1/3 * L)
L_c <- floor(1/3 * L)
#Gold Produced in a week
g <- produce_ore(L_g, params)
s <- produce_ore(L_s, params)
c <- produce_ore(L_c, params)
#Miners paid 1 enchanted gold coin per week
wage_g <- 1
wage_s <- 1
wage_c <- 1
#cost of Mining Gold
glaborcost <- wage_g * L_g
slaborcost <- wage_s * L_s
claborcost <- wage_c * L_c

##**Minting**##
#Assume e is percent of unit of gold lost in minting

e <- runif(1, 0, 0.0002)
#For every unit of gold, x coins can be minted (with spillage accounted for)
x_g <- 10
x_s <- 10
x_c <- 10
M_g <- floor(x_g * g * (1-e))
M_s <- floor(x_s * s * (1-e))
M_c <- floor(x_c * c * (1-e))

#Cost of minting
gmintcost <- 10
smintcost <- 10
cmintcost <- 10

#Spillage and loss accounting
## When implementing repeat simulations, keep stock of difference in M_g with and without floor() to accumulate so less loss

spill_g <- x_g * g - M_g
spill_s <- x_s * s - M_s
spill_c <- x_c * c - M_c

loss_g <- spill_g * 1
loss_s <- spill_s * 0.1
loss_c <- spill_c * 0.01


##**Enchanting Gold**##
#*Country Y is sent M coins to enchant which they do with a*100% success rate
a_g <- 1
a_c <- 1
a_s <- 1

g_enchant <- a_g * M_g
s_enchant <- a_s * M_s
c_enchant <- a_c * M_c

##**Returning Gold*##
#Country Y keeps y% of the coins enchanted as payment since they are the only ones capable of this service.
y_g <- 0.1
y_s <- 0.1
y_c <- 0.1

greserve <- y_g * g_enchant
sreserve <- y_s * s_enchant
creserve <- y_c * c_enchant

gsupply <- g_enchant - greserve
ssupply <- s_enchant - sreserve
csupply <- c_enchant - creserve

#Repaying the cost to create this we have the following cost 
gcost <- glaborcost + gmintcost
scost <- slaborcost + smintcost
ccost <- claborcost + smintcost
#Finally the actual value of generated Money Supply in terms of gold
moneysupply <- (gsupply * 1 - gcost) +  (ssupply * 0.1 - scost) + (csupply * 0.001 - ccost)
moneysupply
```
